version: '3.8'

services:
  api:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "3005:3005"
    environment:
      - NODE_ENV=development
      - DATABASE_HOST=postgres
      - DATABASE_PORT=5432
      - DATABASE_USERNAME=postgres
      - DATABASE_PASSWORD=postgres
      - DATABASE_NAME=satisfaction
      - JWT_SECRET=40c4at-6sCVQXff9hHylOvUOQgfSYT_i_gXkPsBzs5wLbyoNx-jMsOJMI2rM5mumdi9GIFN227H7DILkyid3hg
    depends_on:
      - postgres
    volumes:
      - .:/usr/src/app
      - /usr/src/app/node_modules
    command: npm run start:dev

  postgres:
    image: postgres:15-alpine
    ports:
      - "5433:5432"
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=satisfaction
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data: